--liquibase formatted sql

--changeset barahlush:0.0.1-init-bpms-schema

CREATE TABLE public.users (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR(50) NOT NULL,
                            display_name VARCHAR(100) NOT NULL,
                            email VARCHAR(255) NOT NULL,
                            role VARCHAR(50) NOT NULL,
                            active BOOLEAN NOT NULL DEFAULT TRUE,
                            password_hash VARCHAR(255) NOT NULL,

                            CONSTRAINT uk_users_username UNIQUE (username),
                            CONSTRAINT uk_users_email UNIQUE (email),
                            CONSTRAINT chk_users_role CHECK (role IN ('EMPLOYEE', 'ADMIN'))
);

CREATE TABLE public.process_definitions (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          title VARCHAR(150) NOT NULL,
                                          category VARCHAR(60),
                                          description VARCHAR(500)
);

CREATE TABLE public.step_definitions (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(255) NOT NULL,
                                       type VARCHAR(50) NOT NULL,
                                       process_definition_id BIGINT NOT NULL,

                                       CONSTRAINT fk_step_definitions_process_definition
                                           FOREIGN KEY (process_definition_id)
                                               REFERENCES public.process_definitions (id)
                                               ON DELETE CASCADE,

                                       CONSTRAINT chk_step_definitions_type CHECK (
                                           type IN ('START_EVENT', 'USER_TASK', 'SERVICE_TASK', 'GATEWAY', 'END_EVENT')
                                           )
);

CREATE TABLE public.transitions (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(255) NOT NULL,
                                  from_step_id BIGINT NOT NULL,
                                  to_step_id BIGINT NOT NULL,
                                  condition VARCHAR(100),
                                  process_definition_id BIGINT NOT NULL,

                                  CONSTRAINT fk_transitions_from_step
                                      FOREIGN KEY (from_step_id)
                                          REFERENCES public.step_definitions (id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_transitions_to_step
                                      FOREIGN KEY (to_step_id)
                                          REFERENCES public.step_definitions (id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_transitions_process_definition
                                      FOREIGN KEY (process_definition_id)
                                          REFERENCES public.process_definitions (id)
                                          ON DELETE CASCADE
);

CREATE TABLE public.process_instances (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        process_definition_id BIGINT NOT NULL,
                                        owner_id BIGINT NOT NULL,
                                        current_step_id BIGINT,
                                        status VARCHAR(50) NOT NULL,
                                        started_at TIMESTAMP NOT NULL,
                                        finished_at TIMESTAMP NULL,

                                        CONSTRAINT fk_process_instances_process_definition
                                            FOREIGN KEY (process_definition_id)
                                                REFERENCES public.process_definitions (id),

                                        CONSTRAINT fk_process_instances_owner
                                            FOREIGN KEY (owner_id)
                                                REFERENCES public.users (id),

                                        CONSTRAINT fk_process_instances_current_step
                                            FOREIGN KEY (current_step_id)
                                                REFERENCES public.step_definitions (id),

                                        CONSTRAINT chk_process_instances_status CHECK (
                                            status IN ('RUNNING', 'COMPLETED', 'CANCELLED')
                                            )
);

CREATE TABLE public.process_instance_participants (
                                                    process_instance_id BIGINT NOT NULL,
                                                    user_id BIGINT NOT NULL,

                                                    CONSTRAINT pk_process_instance_participants
                                                        PRIMARY KEY (process_instance_id, user_id),

                                                    CONSTRAINT fk_pip_process_instance
                                                        FOREIGN KEY (process_instance_id)
                                                            REFERENCES public.process_instances (id)
                                                            ON DELETE CASCADE,

                                                    CONSTRAINT fk_pip_user
                                                        FOREIGN KEY (user_id)
                                                            REFERENCES public.users (id)
                                                            ON DELETE CASCADE
);

CREATE INDEX idx_users_username ON public.users (username);
CREATE INDEX idx_users_email ON public.users (email);

CREATE INDEX idx_step_definitions_process_definition_id
    ON public.step_definitions (process_definition_id);

CREATE INDEX idx_transitions_process_definition_id
    ON public.transitions (process_definition_id);

CREATE INDEX idx_transitions_from_step_id
    ON public.transitions (from_step_id);

CREATE INDEX idx_transitions_to_step_id
    ON public.transitions (to_step_id);

CREATE INDEX idx_process_instances_process_definition_id
    ON public.process_instances (process_definition_id);

CREATE INDEX idx_process_instances_owner_id
    ON public.process_instances (owner_id);

CREATE INDEX idx_process_instances_current_step_id
    ON public.process_instances (current_step_id);

CREATE INDEX idx_process_instances_status
    ON public.process_instances (status);

CREATE INDEX idx_pip_user_id
    ON public.process_instance_participants (user_id);


--changeset barahlush:0.0.2-fix-users-role-check
ALTER TABLE public.users DROP CONSTRAINT chk_users_role;

UPDATE public.users
SET role = CASE role
               WHEN 'EMPLOYEE' THEN 'ROLE_USER'
               WHEN 'ADMIN' THEN 'ROLE_ADMIN'
               ELSE role
    END;

ALTER TABLE public.users
    ADD CONSTRAINT chk_users_role
        CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'));