--liquibase formatted sql

--changeset barahlush:0.0.3-create-reports-table

CREATE TABLE public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    content TEXT,

    CONSTRAINT chk_reports_status
        CHECK (status IN ('CREATED', 'COMPLETED', 'ERROR'))
);

CREATE INDEX idx_reports_status ON public.reports (status);